version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3010:3000"
    volumes:
      - .:/myapp
    # env_file:
    #   - .env

